name: Run MATLAB Tests on GitHub-Hosted Runner
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check docker image
        run: |
          docker image ls | grep matlab
      - name: Create license file
        run: |
          mkdir $(pwd)/licenses
          echo $MATLAB_LICENSE >> $(pwd)/licenses/license.lic
        shell: bash
        env:
          MATLAB_LICENSE : ${{ secrets.MATLAB_LICENSE }}
      - name: Verify license
        run: |
          ls ./licenses
          cat licenses/license.lic
      - name: Check license file in container
        run: |
          docker run --rm \
          -v $(pwd)/licenses:/opt/matlab/licenses \
          matlab:r2023a bash -c "ls /opt/matlab/licenses"
      - name: Test Matlab image
        run: |
          docker run --rm \
          --mac-address 02:42:ac:11:ff:ff \
          -v $(pwd)/licenses:/opt/matlab/licenses \
          matlab:r2023a matlab -batch "disp(2+2)"


